# Generated by Django 4.2.13 on 2024-06-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapp', '0002_tokenpair_tokenquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255, unique=True)),
                ('previous_hash', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
