# Generated by Django 4.2.13 on 2024-07-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantumapp', '0005_pendingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='batch_processed',
            field=models.BooleanField(default=False),
        ),
    ]
